SElect a.barcode, P.NAME p_name, A.SLOT, A.MEDIA_STATUS, A.MOUNTS, A.LAST_WRITTEN, A.DATE_EXPIRATION, 
       A.KILOBYTES, A.VALID_IMAGES, A.RETENTION,
       H.NAME h_name, G.ROBOT_NUMBER
from NETBACKUP.MEDIA a, NETBACKUP.VOLUMEPOOL p, NETBACKUP.HOST h, NETBACKUP.VOLUMEGROUP g
where a.volumepool_id = p.volumepool_id
  and A.MEDIA_SERVER_ID = H.HOST_ID(+)
  and A.VOLUMEGROUP_ID = G.VOLUMEGROUP_ID
  and G.ROBOT_NUMBER = 0
  --and P.NAME =  'Documentum'
ORDER by 1, 2
